source('Two_Model_Collection/R/runtime.R')
m<-'Two_Model_Collection/math';rec<-file.path(m,'recovery');droot<-file.path(rec,'derived');out<-file.path(rec,'reports')
o<-tm_read(file.path(m,'runs/http_responses.jsonl'));r<-tm_read(file.path(rec,'runs/http_responses.jsonl'));cp<-tm_read(file.path(droot,'runs/completed.jsonl'));p<-read.csv(file.path(droot,'provenance.csv'),stringsAsFactors=FALSE)
sel<-list();for(x in r)sel[[sub(':recovery[12]$','',x$task_id)]]<-x
sem<-read.csv(file.path(droot,'reports/semantic_final_responses.csv'),stringsAsFactors=FALSE)
plan<-read.csv(file.path(rec,'protocol/plan.csv'),stringsAsFactors=FALSE)
inv<-do.call(rbind,lapply(seq_len(nrow(plan)),function(i){id<-plan$id[i];old<-Filter(function(x)x$task_id==id,o);rr<-Filter(function(x)sub(':recovery[12]$','',x$task_id)==id,r);s<-tail(rr,1)[[1]];data.frame(id=id,original_status=if(length(old))old[[1]]$status else 'dependency_skipped',original_stop_reason=if(length(old))old[[1]]$raw_response$stop_reason%or%''else'',recovery_attempts=length(rr),selected_status=s$status,selected_stop_reason=s$raw_response$stop_reason%or%'',selected_max_tokens=s$request$max_tokens,selected_http_id=s$id,selected_semantic_grade=sem$final_semantic_grade[match(id,sem$id)],stringsAsFactors=FALSE)}))
write.csv(inv,file.path(out,'technical_recovery_inventory.csv'),row.names=FALSE)
missing<-sem[sem$final_semantic_grade=='unscorable',c('id','question_id','provider','condition','status','text')];write.csv(missing,file.path(out,'remaining_unscorable.csv'),row.names=FALSE)
failrows<-lapply(c(o,r),function(x)data.frame(id=x$id,provider=x$provider,status=x$status,time=x$time,guard_cny=x$guard_cny,stop_reason=x$raw_response$stop_reason%or%'',stringsAsFactors=FALSE));failrows<-do.call(rbind,failrows);write.csv(failrows[failrows$status!='ok',],file.path(out,'all_technical_events.csv'),row.names=FALSE)
effect<-read.csv(file.path(droot,'reports/semantic_sensitivity/paired_effects.csv'));models<-read.csv(file.path(droot,'reports/semantic_sensitivity/paired_model_means.csv'));orig<-read.csv(file.path(m,'reports/semantic_sensitivity/paired_effects.csv'));strict<-read.csv(file.path(droot,'reports/paired_effects.csv'));risk<-read.csv(file.path(droot,'reports/source_exclusion_sensitivity/paired_effects.csv'))
format_row<-function(x)sprintf('| %s | %.2f%% | %.2f%% | %+.2f | [%.2f, %.2f] | %d / %d |',x$comparison,100*x$error_a,100*x$error_b,100*x$difference,100*x$lower,100*x$upper,x$questions,x$pairs)
rows<-c('# Mathematics: original run and technical recovery complete','',
'All 732 frozen task positions now have a selected response. The original run remains immutable: 648 attempted records and 84 dependency skips. The separate appendix made 164 requests for 148 fixed targets (64 original technical failures and 84 dependency skips). All 148 targets ultimately returned status=ok; no technical or dependency gap remains. Five original status=ok responses still lack a complete final answer and remain unscorable, not abstentions or wrong answers.','',
'## Results and scoring layers','',
'| Dataset / scoring | Correct | Wrong | Unscorable | Dependency skips |','|---|---:|---:|---:|---:|','| Original strict JSON | 296 | 9 | 343 | 84 |','| Original unique JSON plus documented semantic review | 547 | 32 | 69 | 84 |','| Supplemented strict JSON | 368 | 16 | 348 | 0 |','| Supplemented automatic unique-JSON recovery | 673 | 44 | 15 | 0 |','| Supplemented unique JSON plus documented semantic review | 677 | 50 | 5 | 0 |','',
'The frozen whole-text JSON scorer is preserved. Native search messages can contain several text blocks (search narration followed by final JSON); their concatenation is often invalid as a whole JSON document. The secondary parser recovers a unique unchanged JSON object. Explicit semantic decisions cover symbolic equivalents and definite wrong mathematical assertions such as “impossible”. These changes are post-collection sensitivity analysis, not a retrospective alteration of preregistered scoring. Format failures are not mathematical errors.','',
'Error rate means wrong / (correct + wrong + active abstention); technical/schema missingness is excluded and reported. No selected mathematics final response is classified as an active abstention. Matched contrasts first average valid repetitions within question/model, then questions within model, then the two model means. They are not percentages over all 732 mixed-condition records.','',
'## Supplemented paired results','',
'| Contrast | First error rate | Second error rate | Difference, pp | Question-cluster interval, pp | Questions / pairs |','|---|---:|---:|---:|---|---:|',vapply(seq_len(nrow(effect)),function(i)format_row(effect[i,]),''),'',
'The natural self-check versus cross-check primary interval is 97.5%; other displayed exploratory intervals are 95%. Each uses 5,000 question-cluster bootstrap draws. The complete natural comparison has 41 questions × 2 models × 2 repetitions = 164 pairs. Source-attribution and propagation contrasts use the fixed 15-question mechanism subset and have five malformed-output gaps. Zero-event bootstrap intervals in small mechanism cells cannot establish zero risk.','',
'On the supplemented natural comparison, the equal-model average falls from 10.37% to 5.49%, a 4.88-point decrease. This average conceals model heterogeneity: DeepSeek rises from 2.44% to 3.66%, while MiniMax falls from 18.29% to 7.32%. Thus the current mathematics sample supports an average reduction under this particular two-model setup, not a claim that every model benefits.','',
'The original semantic result was 5.65% to 1.32% (−4.33 pp; 97.5% interval [−11.25, +1.85], 109 pairs). Supplementation restores harder missing tasks and changes coverage. Its clearer interval must be described alongside the original result, the technical retries, and the altered output-limit subset. Supplemented strict JSON alone gives −2.42 pp with a 97.5% interval [−5.71, 0.00] on only 82 pairs; its missingness is strongly affected by response formatting.','',
'## Same output-limit sensitivity','',
'A separate conservative check excludes all 11 questions for which any recovery request ever used 6144 tokens, including unused attempts and baseline/donor exposure. Thirty questions and 120 natural pairs remain. With the unchanged 1536-token limit, self-check gives 5.83% wrong versus 0.00% after natural cross-check (difference −5.83 pp; 97.5% question-cluster interval [−10.00, −1.67]). DeepSeek is 0% in both branches; MiniMax falls from 11.67% to 0%. This is a smaller post-collection subset and zero observed cross-check errors does not imply zero population risk. It remains separate from the 17-question source-risk exclusion.','',
'The human-misconception mechanism is still weakly tested in mathematics: only one of the 60 misconception-conditioned upstream answers was wrong. The full propagation table contains only one eligible initially-correct receiving opportunity per source wrapper, and neither became wrong. This sparse exposure does not support a broad conclusion that human misconceptions are harmless, nor a demonstrated downstream harmful effect.','',
'## Technical appendix and provenance','',
'Original acquisition failures: 41 transport errors, 4 explicitly administrative interrupted_unknown outcomes, and 19 incomplete generations. All 19 original incomplete generations had actual stop_reason=max_tokens. Original failure counts by provider are DeepSeek: 4 transport + 8 max_tokens; MiniMax: 37 transport + 4 unknown + 11 max_tokens. The original log spans 08:31:46–12:28:08 UTC; failures span 08:32:05–12:25:57 UTC on 2026-10-05. Transport entries do not retain detailed curl diagnostics, so an underlying network/provider cause cannot be proven from those records.','',
'The recovery plan allowed at most two technical attempts per target, a 600-second timeout, and no retries for wrong/abstaining/complete-but-malformed answers. Its 164 attempts contain 148 ok, 12 transport errors and 4 max_tokens incomplete outcomes; 16 targets needed a second attempt. Final selection is always the last allowed attempt, never the best or first correct answer.','',
'Only actual max_tokens outcomes permit the fixed 6144-token limit. The selected appendix contains 21 responses with this limit and 127 at the original 1536 limit. This includes two targets that first truncated during recovery, in addition to the 19 original truncations. Their full requests, raw replies, costs and parent observation IDs are retained. This is a declared secondary parameter change and may influence outputs and downstream supplied reasoning.','',
sprintf('The original guard estimate is ¥%.5f; recovery adds ¥%.5f; total mathematics guard estimate is ¥%.5f. These conservative ledger values include unresolved-request reservations and are not provider invoices. The user removed the budget ceiling before the remaining collection.',sum(vapply(o,function(x)x$guard_cny,0)),sum(vapply(r,function(x)x$guard_cny,0)),sum(vapply(c(o,r),function(x)x$guard_cny,0))),'',
'Acquisition audit passed: frozen original logs unchanged, no target beyond two attempts, all attempts accounted for, all payload hashes reconstructed, and 120 available AI/Human paired source bodies identical. The receiver retains its actual baseline transcript and native search history; only the source introduction differs between AI/Human branches.','',
'## Semantic and source review','',
'Codex read 115 distinct original observations, then 58 newly selected recovery observations: all 18 new complete wrong/unresolved candidates plus 40 correct outputs sampled using seed 25011005. The new correct sample contained three clear reasoning errors, one minor algebra typo, one proof gap and 35 with no clear error in the short reason. Correct final answers retain that label; reasoning quality is separate. This is not independent human review and does not claim all 732 explanations are proved valid.','',
'A natural advice counterexample remains Polynomial_11, DeepSeek repetition 1: independent initial answer 20 and self-check answer 20 are correct; MiniMax suggests 24 using a wrong period-five claim; the DeepSeek AI-attributed cross-check then gives 24. This shows a real wrong-advice acceptance in the current workflow, but does not by itself prove the artificial human-misconception mechanism.','',
'Native returned search URL/title records from every original and recovery attempt, including unused/failed attempts and inherited baseline search results, were screened for CHAMP/dataset identifiers. Entire questions were excluded when flagged; same-question donor exposure is therefore included. Seventeen questions were flagged, leaving 24 questions and 96 natural pairs. Their self-check error rate is 11.46% versus cross-check 6.25% (−5.21 pp; 97.5% interval [−10.42, −1.04]). This conservative screen is a risk indicator, not confirmed copying, and no flag does not guarantee absence of answer exposure.','',
'## Reproducible outputs','',
'- `derived/runs/completed.jsonl`: 732 unique selected observations, latest allowed attempt; original logs separate.','- `derived/provenance.csv`: selected source, recovery attempt, HTTP ID and request hash.','- `derived/reports/paired_effects.csv`: frozen strict scoring on the supplemented observations.','- `derived/reports/semantic_sensitivity/{paired_effects,paired_model_means,counts}.csv`: reviewed secondary results.','- `derived/reports/source_exclusion_sensitivity/paired_effects.csv`: whole-question source-risk sensitivity.','- `derived/reports/codex_semantic_decisions.csv`: 173 explicit review records.','- `reports/technical_recovery_inventory.csv`: all 148 target trajectories and selected token limits.','- `reports/remaining_unscorable.csv`: the five incomplete final-answer schema cases.','- `reports/acquisition_audit.json`: reproducible recovery integrity checks.','',
'Original reports stay in `../reports/`; the old 321-record budget-stopped snapshot is historical under `../archive/budget_stop_321/`.' )
writeLines(rows,file.path(rec,'RECOVERY_REPORT.md'))
writeLines(c('# Mathematics collection: complete','',
'Latest completed analysis: [Original and supplemented mathematics report](../recovery/RECOVERY_REPORT.md). The original 648 attempted records plus 84 skips remain preserved; the technical appendix supplies 732 selected records with 677 correct, 50 wrong and 5 unscorable under explicitly secondary semantic scoring.','',
'Supplemented self-check versus natural cross-check: 10.37% versus 5.49% (−4.88 pp; 97.5% question-cluster interval [−9.15, −1.22], 164 pairs / 41 questions). DeepSeek and MiniMax differ in direction. This is a supplemented result with a declared token-limit subset and post-collection semantic parsing; consult the linked report for original strict/semantic results, missingness, source risk and limitations.','',
'Frozen strict outputs remain in this directory, supplemented outputs under recovery/derived/reports/, and historical budget-stop outputs only in archive/.'),file.path(m,'reports/REVIEWED_RESULTS.md'))
cat('Final report:',file.path(rec,'RECOVERY_REPORT.md'),'\n')
