"""Select the first 120 quality-qualified items before receiver collection.

No model calls. Source/content reviews are inputs, not generated by this script.
"""
import json
from pathlib import Path
from collections import Counter
from study import MODELS, read_jsonl, digest, timestamp
from freeze_materials import propose
from collect import write_json

ROOT = Path(__file__).resolve().parent

def main():
    questions = read_jsonl(ROOT/'data/main_candidate_questions.jsonl')
    records = read_jsonl(ROOT/'runs/main_materials/responses.jsonl')
    rejected = json.loads((ROOT/'data/main_material_rejections.json').read_text())
    reviews = json.loads((ROOT/'data/main_content_reviews.json').read_text())
    materials, audit, missing = propose(questions, records, rejected)
    selected, decisions = [], []
    for q in questions:
        keys = [f'{q["question_id"]}:{p}:{t}' for p in MODELS for t in ['correct','wrong']]
        absent = [k for k in keys if k not in materials]
        unchecked = [k for k in keys if k in materials and
                     reviews.get(k, {}).get('material_sha256') != digest(materials[k])]
        if len(selected) == 120:
            status = 'reserve_after_target_reached'
        elif absent:
            status = 'excluded_material_quality'
        elif unchecked:
            raise ValueError('Cannot skip an earlier unreviewed eligible item: '+q['question_id'])
        else:
            status = 'retained'
            q = dict(q)
            q['original_pairing_direction'] = q['pairing_direction']
            q['pairing_direction'] = len(selected) % 2
            q['split'] = 'main'
            selected.append(q)
        decisions.append({'question_id':q['question_id'],'status':status,
                          'missing_material_keys':absent,'unchecked_material_keys':unchecked})
    dev = read_jsonl(ROOT/'data/candidates.jsonl')[:24]
    assert not {q['question_id'] for q in dev} & {q['question_id'] for q in selected}
    assert not {q['question'].strip().lower() for q in dev} & {q['question'].strip().lower() for q in selected}
    target = ROOT/'data/main_questions.jsonl'
    content = ''.join(json.dumps(q,ensure_ascii=False)+'\n' for q in selected)
    if target.exists() and target.read_text()!=content:
        raise ValueError('Refusing to overwrite a different formal sample')
    target.write_text(content)
    write_json(ROOT/'data/main_selection_audit.json',{
        'timestamp':timestamp(),'target':120,'retained':len(selected),'candidate_count':len(questions),
        'rule':'First six-slot quality-qualified items in frozen candidate order; no receiver outcomes used.',
        'pairing_rule':'Alternate cycle direction across retained order, giving 60 questions per direction at N=120.',
        'questions_sha256':digest(selected),'materials_raw_sha256':digest(records),
        'independent_human_review_complete':False,'counts':dict(Counter(d['status'] for d in decisions)),
        'decisions':decisions})
    print(json.dumps({'retained':len(selected),'decisions':dict(Counter(d['status'] for d in decisions))}))

if __name__=='__main__':main()
