# Separate post-hoc reading of completed N0 responses that the frozen parser cannot score.
source('Followup_Validation/R/common.R');p<-file.path(VROOT,'baseline_review');g<-read.csv(file.path(p,'responses.csv'))
ids<-c('CHAMP:P_Polynomial_50:deepseek:r1:N0','CHAMP:P_Sequence_21:deepseek:r2:N0','CHAMP:P_Number-Theory_17:kimi:r2:N0','CHAMP:P_Polynomial_17:minimax:r1:N0','CHAMP:P_Number-Theory_17:minimax:r2:N0','CHAMP:P_Polynomial_17:minimax:r2:N0','CHAMP:P_Polynomial_47:minimax:r1:N0','CHAMP:P_Number-Theory_12:minimax:r2:N0','CHAMP:P_Sequence_19:minimax:r2:N0','CHAMP:P_Combinatorics_20:minimax:r1:N0')
grades<-c('correct','correct','correct','incorrect','correct','incorrect','correct','incorrect','incorrect','incorrect')
notes<-c('Final string a = -5 is unambiguous but outside the numeric parser grammar.','Correct final 2500 and recurrence proof; literal newline inside the quoted JSON reason makes its encoding invalid.','Final string 7744 = 88² identifies the requested square number.','Prose conclusion n is false: continuity forces a single sign of f(x)-x and excludes all two-cycles.','Final string 7744 (=88²) identifies the requested square number.','Final n(n-1) is false; the displayed example itself fails to attain the asserted maximum.','Plain-text answer:120 is correct, although no JSON object is provided.','Includes false extra answer 75; 75²=5625 does not end in 75.','Final 1 follows a false period-12 claim; the sequence has period 7 and the answer is -1.','JSON omits abstain; final 7 is wrong, and the claimed computed dynamic program has no supporting transitions.')
x<-data.frame(task_id=ids,semantic_grade=grades,evidence=notes,reviewer='Codex AI; targeted post-hoc format review')
need<-g$task_id[g$status=='ok'&g$grade=='unscorable'];stopifnot(setequal(need,x$task_id),length(need)==10)
write.csv(x,file.path(p,'format_annotations.csv'),row.names=FALSE)
g$semantic_grade<-g$grade;ix<-match(x$task_id,g$task_id);g$semantic_grade[ix]<-x$semantic_grade
t<-as.data.frame(table(g$provider,g$semantic_grade));names(t)<-c('provider','semantic_grade','n');write.csv(t,file.path(p,'format_sensitivity_counts.csv'),row.names=FALSE)
writeLines(c('# Completed baseline outputs missed by the frozen format rules','',
 'Codex read all ten status-ok mathematical N0 responses that the frozen parser marked unscorable. Five have a clear correct final answer; five have a clear wrong final answer. This is a separate post-hoc semantic sensitivity, not a change to the frozen grades. Other baseline unscorable responses were incomplete or transport failures and are not silently recovered.', '',
 'The parser accepts a numeric answer string, but does not recognize strings such as a = -5 or 7744 = 88²; malformed JSON and plain-text answers also fail its rules. Some nonnumeric answers, such as n(n-1), are substantive wrong conclusions rather than mere encoding issues. Both directions must be retained.', '',
 'This also affects availability: an invalid N0 object prevents some later branches from being requested. Re-reading its meaning cannot reconstruct those uncollected branches. Bounds and skipped-input records remain necessary.'),file.path(p,'format_review.md'))
cat('Ten completed baseline format failures reviewed: five correct, five wrong.\n')
