library(jsonlite)
source('Two_Model_Collection/math/R/scoring.R')
root<-'Two_Model_Collection/math'
tasks<-read.csv(file.path(root,'protocol/tasks.csv'),check.names=FALSE,stringsAsFactors=FALSE)
subset<-read.csv(file.path(root,'protocol/mechanism_subset.csv'))
p<-fromJSON(file.path(root,'protocol/prompts.json'),simplifyVector=FALSE)$questions
refs<-fromJSON(file.path(root,'protocol/researcher_reference.json'),simplifyVector=FALSE)
checks<-list()
check<-function(n,b){if(!isTRUE(b))stop(n);checks[[n]]<<-TRUE}
check('732_unique_tasks',nrow(tasks)==732L&&!anyDuplicated(tasks$id))
check('41_questions',length(unique(tasks$question_id))==41L)
check('15_subset_3_per_family',nrow(subset)==15&&all(table(subset$family)==3))
check('conditions_counts',all(table(tasks$condition)[c('neutral_initial','self_check','A0_AI')]==164)&&all(table(tasks$condition)[c('misconception_initial','A0_Human','A1_AI','A1_Human')]==60))
check('all_dependencies_exist',all(c(tasks$baseline_id,tasks$donor_id)[nzchar(c(tasks$baseline_id,tasks$donor_id))]%in%tasks$id))
idx<-setNames(seq_len(nrow(tasks)),tasks$id)
check('dependencies_before_tasks',all(vapply(seq_len(nrow(tasks)),function(i){d<-c(tasks$baseline_id[i],tasks$donor_id[i]);all(idx[d[nzchar(d)]]<i)},TRUE)))
check('providers_different_for_peers',all(tasks$provider[nzchar(tasks$donor)]!=tasks$donor[nzchar(tasks$donor)]))
j<-function(a,ab=FALSE,r='A concise solution.')as.character(toJSON(list(reason=r,abstain=ab,answer=a),auto_unbox=TRUE))
check('41_correct_references_score_correct',all(vapply(refs,function(q)math_score(j(q$reference_answer),q$question_id,refs)$label=='correct',TRUE)))
for(id in paste0('CHAMP:P_Inequality_',c(8,15,24)))check(paste0('nonattainment_wrong_',id),math_score(j('No minimum is attained; the infimum is 0'),id,refs)$label=='wrong')
check('symbolic_remainder_wrong',math_score(j('x-1'),'CHAMP:P_Polynomial_1',refs)$label=='wrong')
check('symbolic_limit_wrong',math_score(j('u-v'),'CHAMP:P_Sequence_28',refs)$label=='wrong')
check('explicit_abstention',math_score(j('',TRUE),'CHAMP:P_Sequence_28',refs)$label=='abstain')
check('conflicting_abstention',math_score(j('0',TRUE),'CHAMP:P_Sequence_28',refs)$conflict)
check('reason_conflict_separate',math_score(j('0',FALSE,'The minimum is not attained.'),'CHAMP:P_Inequality_8',refs)$conflict)
check('not_last_number',math_score(j('x-1 is zero at x=1, so x-1'),'CHAMP:P_Polynomial_1',refs)$label=='unscorable')
check('arithmetic_safe',is.na(math_numeric('system("echo unsafe")')))
check('negative_sign_preserved',math_numeric('-9')==-9)
check('fraction',math_numeric('-9/2')==-4.5)
check('boxed_zero',math_numeric('\\boxed{0}')==0)
check('unknown_multiple_answer_review',math_score(j('0 or 1'),'CHAMP:P_Sequence_28',refs)$needs_review)
check('invalid_json_not_abstain',math_score('{','CHAMP:P_Sequence_28',refs)$label=='unscorable')
check('same_source_wrapper_body',all(vapply(p,function(q)identical(sub('^[^\n]+\n','',q$prompts$A0_AI),sub('^[^\n]+\n','',q$prompts$A0_Human))&&identical(sub('^[^\n]+\n','',q$prompts$A1_AI),sub('^[^\n]+\n','',q$prompts$A1_Human)),TRUE)))
write_json(list(status='passed',check_count=length(checks),checks=checks),file.path(root,'protocol/checks.json'),pretty=TRUE,auto_unbox=TRUE)
cat(length(checks),'offline checks passed. No model calls.\n')
