# Synthetic fixture isolated from all real run directories; no network.
library(jsonlite)
realroot<-'Two_Model_Collection/math';testroot<-tempfile('math-analysis-fixture-')
dir.create(file.path(testroot,'protocol'),recursive=TRUE);dir.create(file.path(testroot,'runs'))
file.copy(file.path(realroot,'protocol/tasks.csv'),file.path(testroot,'protocol/tasks.csv'))
tasks<-read.csv(file.path(realroot,'protocol/tasks.csv'),stringsAsFactors=FALSE)
ids<-head(read.csv(file.path(realroot,'protocol/mechanism_subset.csv'))$question_id,2)
refs<-fromJSON(file.path(realroot,'protocol/researcher_reference.json'),simplifyVector=FALSE)
gold<-setNames(vapply(refs,`[[`,'','reference_answer'),vapply(refs,`[[`,'','question_id'))
tt<-tasks[tasks$question_id%in%ids,]
fixture<-lapply(seq_len(nrow(tt)),function(i){t<-tt[i,];wrong<-t$condition%in%c('misconception_initial','A1_AI')
 list(id=t$id,status='ok',search_requested=0L,text=as.character(toJSON(list(reason='SYNTHETIC FIXTURE ONLY; not an observed response.',abstain=FALSE,answer=if(wrong)'-999'else gold[[t$question_id]]),auto_unbox=TRUE)))})
writeLines(vapply(fixture,function(x)as.character(toJSON(x,auto_unbox=TRUE)),''),file.path(testroot,'runs/completed.jsonl'))
Sys.setenv(MATH_ANALYSIS_ROOT=testroot);source(file.path(realroot,'R/analyse.R'));Sys.unsetenv('MATH_ANALYSIS_ROOT')
res<-read.csv(file.path(testroot,'reports/paired_effects.csv'))
stopifnot(res$difference[res$comparison=='natural_crosscheck']==0,res$difference[res$comparison=='propagation_AI']==1,res$difference[res$comparison=='attribution_A1']==-1)
paths<-read.csv(file.path(testroot,'reports/propagation_path_counts.csv'))
stopifnot(all(paths$path_per_eligible[paths$condition=='A1_AI']==1),all(paths$path_per_eligible[paths$condition=='A1_Human']==0))
ix<-fromJSON(file.path(testroot,'reports/source_input_interaction.json'));stopifnot(ix$difference==-1)
summary<-fromJSON(file.path(testroot,'reports/summary.json'));stopifnot(summary$completed==56,!summary$scope_complete,summary$not_collected==676)
write_json(list(status='passed',synthetic_only=TRUE,network_calls=0L,checks=c('paired_effects','propagation_denominators','four_branch_interaction','partial_coverage','semantic_review_export')),file.path(realroot,'reports/analysis_fixture_checks.json'),pretty=TRUE,auto_unbox=TRUE)
unlink(testroot,recursive=TRUE)
cat('Synthetic paired-analysis checks passed; fixture removed.\n')
