// Layout only. R prepares every experimental value, label, chart and note.
import fs from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
const require=createRequire(import.meta.url);
const {Presentation,PresentationFile}=await import(pathToFileURL(require.resolve('@oai/artifact-tool')).href);
const root=process.cwd(),skill=process.env.SKILL_DIR,python=process.env.RUNTIME_PYTHON;
if(!skill||!python)throw Error('Set SKILL_DIR and RUNTIME_PYTHON');
const {resolvePresentationFont,applyPresentationChartFont,finalizePresentation}=await import(pathToFileURL(path.join(skill,'container_tools/artifact_tool_utils.mjs')));
const font=resolvePresentationFont();
const d=JSON.parse(await fs.readFile('Submission_Pack/evidence/integrated_data.json','utf8'));
const notes=JSON.parse(await fs.readFile('Submission_Pack/evidence/integrated_notes.json','utf8'));
const build=path.join(root,'.submission-build/integrated-20261004');await fs.mkdir(build,{recursive:true});
const p=Presentation.create({slideSize:{width:1280,height:720}});
const navy='#142C40',teal='#147E77',red='#C45F48',muted='#657586',bg='#FAFBFD';
function text(s,t,x,y,w,h,size=30,color=navy,bold=false){const b=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});b.text=t;b.text.style={typeface:font,fontSize:size,bold,color,autoFit:'none'};return b;}
function slide(i,title=notes.titles[i-1]){const s=p.slides.add();s.background.fill=bg;text(s,title,68,42,1140,108,43,navy,true);text(s,String(i),1162,673,50,30,17,muted);s.speakerNotes.textFrame.setText(notes.notes[i-1]);return s;}
function body(s,lines,top=182,step=96,size=31){lines.forEach((t,i)=>text(s,t,76,top+i*step,1124,84,size));}
function table(s,values,top=175,height=340,widths=null,size=26){const n=values[0].length;const t=s.tables.add({rows:values.length,columns:n,left:72,top,width:1136,height,columnWidths:widths||Array(n).fill(1136/n),values});for(let r=0;r<values.length;r++)for(let c=0;c<n;c++){const cell=t.getCell(r,c);cell.fill=r===0?navy:(r%2?'#F0F4F7':'#FFFFFF');cell.text.style={typeface:font,fontSize:size,color:r===0?'#FFFFFF':navy,bold:r===0};}return t;}
function bars(s,id,{top=182,height=340,left=90,width=1100}={}){
 const data=d.charts[id];const palette=id==='misleading'?[muted,red,red]:[muted,teal];
 const series=data.series?data.series.map((z,i)=>({name:z.name,values:z.values,valuesFormatCode:'0.00%',fill:palette[i]})):[{name:'Error rate',values:data.values,valuesFormatCode:'0.00%',fill:teal,points:data.values.map((_,idx)=>({idx,fill:palette[idx]}))}];
 const c=s.charts.add('bar',{position:{left,top,width,height},categories:data.categories,series,barOptions:{direction:'column',grouping:'clustered'},hasLegend:!!data.series,legend:{position:'bottom',textStyle:{fontSize:22}},dataLabels:{showValue:true,position:'outEnd',textStyle:{fontSize:25,bold:true}},xAxis:{textStyle:{fontSize:24}},yAxis:{min:0,max:data.max,majorUnit:data.max===.1?.02:.25,numberFormatCode:'0%',textStyle:{fontSize:22}}});applyPresentationChartFont(c,{fontFamily:font});return c;
}
function effect(s,x,extra){text(s,`${x.change_label}   /   ${x.interval_label}`,76,548,1130,50,28,teal,true);text(s,extra,76,613,1130,57,24,muted);}
let s=slide(1,'Can We Trust AI More\nAfter Cross-Checking?');text(s,'COMP2501',76,268,1100,45,29,teal,true);text(s,d.authors.join('  /  '),76,340,1100,65,36,navy,true);text(s,'Natural cross-checking, misleading advice and uncertainty',76,464,1100,85,32);text(s,'Integrated results  /  4 October 2026',76,590,1100,45,25,muted);
s=slide(2);body(s,['Professor LUO RUIBANG asked who would completely trust AI.','I raised my hand because I use different agents to cross-check.','Does that extra check actually reduce errors?','Can a wrong suggestion change a correct answer?']);text(s,'Paraphrased from LINYUNIAN’s recollection of the class',76,624,1110,35,22,muted);
s=slide(3);table(s,[['Question','Evidence'],['Does natural cross-checking help?','100 factual + 41 mathematical questions'],['Can wrong advice mislead?','Original controlled study: 120 facts'],['What does verification change?','New prompt ablation: 36 facts']],180,345,[540,596],29);text(s,'Separate studies and denominators. No pooling of old and new replies.',76,575,1110,70,27,muted);
s=slide(4);table(s,[['Branch','Information','Action'],['N0','Question only','Independent answer'],['N1','Question + own N0','Self-check'],['N2','Same N0 + another model’s N0','Cross-model check'],['N3','Same N0 + identical peer advice','Explicit verification']],168,350,[140,640,356],25);text(s,'DeepSeek, Kimi and MiniMax each use both other models across two repeats.',76,545,1130,65,28,teal,true);text(s,'Parallel branches from N0. One receiver revision, no third judge or tools.',76,618,1120,50,24,muted);
s=slide(5);body(s,['100 previously studied date questions, with fresh API responses.','41 CHAMP questions across five mathematics topics.','Three different model APIs, two independent repeats.','3,829 scorable answers from 4,032 planned outputs.'],175,95,31);text(s,'Missing, truncated and invalid responses remain separate from abstention.',76,615,1120,62,24,muted);
s=slide(6);text(s,'Wrong answers',76,172,1100,70,48,red,true);text(s,'divided by correct + wrong + explicit abstentions',76,251,1110,80,34);body(s,['We report correct answers and abstentions separately.','A correct answer does not certify every step in its explanation.','Main comparisons show matched samples and uncertainty intervals.'],370,80,28);text(s,'R analysis resamples whole questions, keeping model repeats together.',76,636,1110,33,22,muted);
s=slide(7);bars(s,'facts');effect(s,d.facts[0],`${d.facts[0].count_label}. The interval includes zero.`);
s=slide(8);bars(s,'math');effect(s,d.math[0],'199/246 planned pairs, covering 39/41 questions. Vertical scale: 0–10%.');
s=slide(9);bars(s,'models',{top:180,height:380});text(s,'DeepSeek and Kimi increase; MiniMax decreases in this selected sample.',76,585,1125,48,27,teal,true);text(s,'Matched pairs: 195, 197 and 186. Descriptive differences, not a model ranking.',76,637,1110,35,22,muted);
s=slide(10);bars(s,'misleading');text(s,'+18.78 points for wrong answers; +6.40 for wrong answers with reasons',76,545,1120,66,28,red,true);text(s,'719 units per group. Original controlled study, exploratory all-unit comparison.',76,619,1120,46,23,muted);
s=slide(11);bars(s,'verification');effect(s,d.clean[0],'Same wrong advice, 210 matched pairs. Basic permission to abstain stays in both.');
s=slide(12);bars(s,'reminder',{top:172,height:315});text(s,`${d.reminder[0].change_label}   /   ${d.reminder[0].interval_label}`,76,505,1130,45,27,teal,true);table(s,[['Outcome','Without reminder','With reminder'],['Correct','48 / 210','38 / 210'],['Abstain','56 / 210','89 / 210']],566,96,[420,358,358],23);
s=slide(13);text(s,'1,980 digits “2”, divided by 1,982: the remainder is 0.',76,164,1110,60,32,teal,true);table(s,[['Response','Remainder'],['Kimi self-check','0  (correct)'],['MiniMax independent advice','220  (wrong CRT step)'],['Kimi cross-model check','220  (adopts the wrong step)']],251,272,[820,316],29);text(s,'A separate coefficient problem improved from −120 to 120 with correct peer advice.',76,565,1110,65,27);text(s,'Actual saved outputs. R independently verifies remainder 0. Cases are illustrative.',76,638,1110,35,22,muted);
s=slide(14);body(s,['Missing answers on difficult problems can change the overall result.','Selected dates and public problems do not represent all AI use.','AI reasoning reviewers also make mistakes; rigor gains remain uncertain.','We did not test human outcomes or isolate model diversity from extra advice.'],174,105,29);
s=slide(15);body(s,['Natural cross-checking has no established advantage over self-checking here.','Assigned wrong advice can increase the chance of a wrong answer.','An abstention reminder can reduce errors while also reducing correct answers.','Cross-checking cannot justify 100% trust.'],172,105,31);
s=slide(16);body(s,['Keep initial answers independent before sharing a preferred answer.','Label assumptions in your prompt and compare the supporting evidence.','Preserve uncertainty when the evidence does not settle the question.','Use sources or executable checks for consequential claims.'],172,103,30);text(s,'Proposed practice. External retrieval and calculators were not tested here.',76,628,1110,39,23,muted);
s=slide(17);table(s,[['Source','Role in the project'],['Google SimpleQA Verified','Selected factual questions'],['CHAMP, ACL Findings 2024','New mathematical questions and references'],['Huang et al., ICLR 2024','Limits of intrinsic self-correction'],['Dhuliawala et al., ACL Findings 2024','Chain-of-Verification']],170,354,[570,566],26);text(s,'Earlier exploration also used MathTrap and GSM-Symbolic examples.',76,565,1110,55,28);text(s,'Full links and pinned dataset versions appear in the report and slide notes.',76,633,1110,37,22,muted);
s=slide(18);text(s,'LINYUNIAN and PAN ZHENGYU',76,178,1110,70,40,teal,true);body(s,['R processing with archived prompts, raw outputs and source records.','Codex assisted implementation, analysis, review and writing.','Earlier Claude Code review used its configured Kimi backend.'],302,89,29);text(s,'github.com/ThomasLin070217/comp2501-ai-reliability',76,585,1110,52,29,navy,true);text(s,'Questions',76,643,800,40,27,muted);
s=slide(19);table(s,[['Original endpoint','Ordinary condition','Comparison'],['Wrong-only vs wrong + reason','5 / 154 harmful flips','3 / 154'],['Same wrong advice + verification','3 / 154 harmful flips','0 / 154'],['Correct advice + verification','76 / 322 repairs','45 / 322']],180,332,[530,350,256],26);text(s,'We did not establish that explanations increase harmful flips.',76,553,1110,65,29,teal,true);text(s,'Sparse flip events and lost useful corrections remain part of the evidence.',76,626,1110,42,24,muted);
s=slide(20);table(s,[['Sensitivity','Result','Limit'],['Recover clear format failures','Facts −0.17 pp; math −2.45 pp','Adjusted intervals include 0'],['All planned mathematics pairs','Difference bound −14.23 to +13.82 pp','Missing outcomes can reverse direction'],['Partial reasoning-label audit','13 vs 8 incorrect reasons / 206','95% interval includes 0']],176,350,[410,395,331],25);text(s,'Sensitivity results stay separate from the frozen primary analysis.',76,572,1110,60,29,teal,true);text(s,'Eight disagreements among 52 inspected reviewer labels. Others are not fully verified.',76,635,1110,39,22,muted);
const candidate=path.join(build,'candidate.pptx');await(await PresentationFile.exportPptx(p)).save(candidate);
for(let i=0;i<p.slides.items.length;i++){const png=await p.export({slide:p.slides.items[i],format:'png',scale:1});await fs.writeFile(path.join(build,`slide-${i+1}.png`),new Uint8Array(await png.arrayBuffer()));}
const final=path.resolve(root,process.env.OUTPUT_PPTX||'.submission-build/integrated-20261004/final/presentation.pptx');await fs.mkdir(path.dirname(final),{recursive:true});
const tables=[3,4,12,13,17,19,20];
await finalizePresentation({workspaceDir:root,candidatePath:candidate,finalPath:final,pythonExecutable:python,integrityValidatorPath:path.join(skill,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(skill,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-heading-fit',...tables.flatMap(n=>['--require-native-table-slide',String(n)])],explicitTotalSlideCount:20,requiredNativeTableOwnerSlides:tables,requiredNativeChartOwnerSlides:[7,8,9,10,11,12],materializeLiteralChartWorkbooks:true,fontPolicy:{basis:'design',families:[font]},verifyArtifactToolImport:true,receiptPath:path.join(build,`validation-${Date.now()}.json`)});
console.log(`Created ${final}; font ${font}`);
