# R prepares all added values and speaker notes; JS only places objects.
source('Peer_Misleading_Study/R/core.R')
d<-read_json('Submission_Pack/evidence/artifact_content.json')
n<-jsonlite::fromJSON('Natural_Crosscheck/reports/presentation_data.json')
r<-n$rates;r$error_rate<-r$error_pct/100
for(st in c('correct','wrong','abstain'))r[[paste0(st,'_rate')]]<-r[[st]]/r$n
fx<-read.csv('Natural_Crosscheck/reports/effects.csv');tx<-read.csv('Natural_Crosscheck/reports/transitions.csv')
d$natural<-list(rates=unname(lapply(seq_len(nrow(r)),function(i)as.list(r[i,]))),summary=n$summary)
d$natural$comparison_labels<-lapply(c('facts','mathematics'),function(dmn){x<-subset(fx,provider=='pooled'&metric=='error'&domain==dmn&comparison=='N2-N1');list(domain=dmn,text=if(dmn=='facts')sprintf('Primary pairs: %+.2f pp; 95%% interval [%.2f, %.2f]',x$difference_pp,x$ci_low_pp,x$ci_high_pp)else sprintf('Peer minus self: %+.2f pp; descriptive comparison',x$difference_pp),n=x$n)})
z<-subset(tx,domain=='facts'&provider=='pooled'&comparison=='N2-N1')
mat<-xtabs(n~from+to,z)[c('correct','incorrect','abstain'),c('correct','incorrect','abstain')]
d$natural$transition_table<-c(list(c('Self-check','Peer correct','Peer wrong','Peer abstain')),lapply(1:3,function(i)c(c('Correct','Wrong','Abstain')[i],as.character(mat[i,]))))
url<-'https://github.com/ThomasLin070217/comp2501-ai-reliability'
notes<-c(
 'Introduce LINYUNIAN and PAN ZHENGYU and the question: can cross-checking justify more trust in AI? Reliability here means fewer wrong final outputs, not measured human trust or a guarantee of truth.',
 "Tell the classroom story as LINYUNIAN's recollection: Professor LUO RUIBANG asked who would completely trust AI. LINYUNIAN raised a hand because multiple agents cross-check responses. Explain that this project tests that reason for trust. These slide sentences are a paraphrase, not a verbatim quotation of the professor.",
 'Explain A as natural cross-checking, B as controlled wrong input, C as structured verification. The original B/C protocol and endpoints remain unchanged. A is an explicitly post-hoc addition on previously studied questions, frozen before its new calls. Domains remain separate.',
 'Each of three different models answers alone. That answer is N0 and is also another receiver\'s peer material. The receiver branches to N1 self-check, N2 natural peer-check, N3 structured peer-check. Primary N2-N1 controls for an extra receiver attempt. Total deployment cost still includes the donor. The skill itself was unavailable, so this is a defined one-round workflow.',
 paste('Read the factual bars with a 0-100% axis. Common-four samples are used in bars; pairwise contrasts can have different denominators.',d$natural$comparison_labels[[1]]$text,'Do not call an interval crossing zero evidence of equivalence. Questions are previously studied, not a fresh population sample.'),
 paste('Read the mathematics bars with the same 0-100% scale.',d$natural$comparison_labels[[2]]$text,'Only13items and four families are represented. N0 has10field errors,8already-correct explanation endpoints and2addition errors. N1 fixes the8field errors; N2 fixes the remaining2arithmetic errors. This is descriptive, not a universal logic benchmark.'),
 'Read the paired facts table from self-check rows to peer-check columns. It shows both beneficial and harmful changes, including uncertainty becoming a wrong answer. Counts are paired alternatives, not sequential N1-to-N2 conversations. The table includes all valid N1/N2 pairs.',
 'Explain original B/C conditions. A different model produced advice for researcher-assigned targets. This estimates response to controlled advice, not the frequency with which another model naturally errs. C2/C3 and C4/C5 use exactly matched suggestions. The previous prespecified harmful-flip endpoints remain in the report.',
 'Read both error-rate bar charts. C0/C1/C2: 46.04%,64.81%,52.43%; C2/C3:52.43%,35.88%. Error is wrong/(correct+wrong+abstain), all719. Wrong-only and wrong-plus-reason are +18.78/+6.40 pp vs neutral; structured is -16.55 pp vs ordinary same wrong advice. These all-unit comparisons are post hoc. Wrong explanations were not more harmful than wrong-only in the original harmful-flip endpoint.',
 'Read the paired C2/C3 outcomes:144 wrong-to-abstain,5 wrong-to-correct,21 abstain-to-wrong,9 correct-to-wrong. The net reduction119 is not119 successful factual corrections. Correct answers also decline. Explicit uncertainty can be useful without finding the answer.',
 'The correct-advice control is a counterweight:76/322 initially wrong units are repaired by C4,45/322 by C5. Difference -9.63pp,95% cluster interval[-14.38,-5.25]. Less error and less useful answering can coexist; report both, do not impose a universal utility score.',
 'Explain the equilateral triangle example from MathTrap:perimeter30 implies side10 and height5sqrt(3),about8.66,so height10 is inconsistent. Direct area50 ignores feasibility. A proved inconsistency is correct, not an abstention. This published example is a historical failure, not a claim every model now fails it.',
 'Define final-answer scoring and uncertainty. All current processing is R. The original math supplement has13/16 initial field errors whose explanations already reach the correct endpoint. Do not relabel those as purely failed reasoning. API or format failures are separate. Correct dates do not validate all explanatory claims.',
 'Use the original Notepad++ example:official date28June2020. MiniMax C0 cannot confirm,C1/C2 say29June,C3 withdraws. The phrase as confirmed by the official release notes appeared without a search tool. A confidence phrase is not evidence retrieval. Preserve the reverse example in the report.',
 'Explain selected questions and exploratory analyses. Natural fact N2-N1 differs by receiver: DeepSeek-14.29pp, Kimi+20.59pp, MiniMax-21.21pp. These are descriptive exploratory strata with different donor directions. Earlier AI review covered240pairs/451responses; new review reads319responses including151math responses, not an independent human audit. No human source-label experiment or human behavior measurement was performed.',
 'Answer: conditionally, not automatically. Natural fact error difference is-4.90pp with interval spanning zero. Two arithmetic errors remained after self-checking and were repaired with peer input;8earlier math errors were field/reason conflicts. Controlled wrong advice raises error; structured checking reduces it mainly by abstaining. There is no100%guarantee or universal best method.',
 'Offer practical advice as a proposed workflow: separate assumptions from facts, seek independent answers before showing your own guess, compare evidence and resolve contradictions, retain uncertainty and externally verify consequential claims. External retrieval/calculators were not tested in these experiments.',
 'Name both team members and acknowledge public datasets and papers, R packages, Codex implementation/drafting/review and earlier Claude Code review via Kimi. Do not invent independent human validation or individual student implementation roles.'
)
durations<-rep(60,18);durations[c(1,18)]<-30;durations[c(4,5,8,9)]<-75
stopifnot(sum(durations)==1080,length(notes)==18)
sources<-c(paste0(url,'/blob/main/docs/experiment-architecture-v2.md'),paste0(url,'/blob/main/CHAT_CONTEXT.md#u31'),paste0(url,'/blob/main/docs/experiment-architecture-v2.md'),paste0(url,'/blob/main/Natural_Crosscheck/protocol/freeze.json'),rep(paste0(url,'/tree/main/Natural_Crosscheck/reports'),3),paste0(url,'/blob/main/docs/experiment-plan-v1.md'),rep(paste0(url,'/blob/main/Submission_Pack/补充分析_2026-10-03.md'),2),paste0(url,'/blob/main/Peer_Misleading_Study/reports/main_r/effects.csv'),'https://aclanthology.org/2024.emnlp-main.915/ (Table 13)',paste0(url,'/blob/main/Math_Supplement/reports/supplementary/semantic-review.md'),'https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Changes-v7#788',paste0(url,'/blob/main/CHAT_CONTEXT.md'),paste0(url,'/tree/main/Natural_Crosscheck/reports'),'https://aclanthology.org/2024.findings-acl.212/','https://huggingface.co/datasets/google/simpleqa-verified\nhttps://openreview.net/forum?id=IkmD3fKBPQ\nhttps://aclanthology.org/2024.findings-acl.212/\nhttps://aclanthology.org/2024.emnlp-main.915/\nhttps://machinelearning.apple.com/research/gsm-symbolic')
d$notes<-as.list(paste0(durations,' seconds. ',notes,'\nSources: ',sources));d$order<-0:17
write_json(d,'Submission_Pack/evidence/artifact_content.json')
writeLines(c('# Speaker notes: Can We Trust AI More After Cross-Checking?','', 'LINYUNIAN and PAN ZHENGYU. Suggested 18-minute talk (1080 seconds), plus 2 minutes Q&A. Suggested speaking split: LINYUNIAN slides1-9 and PAN ZHENGYU slides10-18; this is a rehearsal suggestion, not a claim about research contributions.','',unlist(lapply(1:18,function(i)c(paste('## Slide',i),d$notes[[i]],'')))),'Submission_Pack/speaker_notes.md')
prov<-read_json('Submission_Pack/evidence/provenance.json');extra<-c('Natural_Crosscheck/reports/tables.csv','Natural_Crosscheck/reports/effects.csv','Natural_Crosscheck/reports/summary.json','Natural_Crosscheck/reports/transitions.csv');prov$source_sha256<-c(prov$source_sha256,setNames(lapply(extra,file_sha),extra));write_json(prov,'Submission_Pack/evidence/provenance.json')
cat('Natural results and18-slide notes exported in R.\n')
