# Offline artifact-to-evidence validation in R. No experimental outputs are changed.
library(jsonlite);library(xml2);library(digest)
pack<-'Submission_Pack';d<-fromJSON(file.path(pack,'evidence/integrated_data.json'),simplifyVector=FALSE)
ppt<-file.path(pack,'COMP2501_presentation.pptx');pdf<-file.path(pack,'COMP2501_report.pdf')
build<-'.submission-build/integrated-20261004';dir.create(file.path(build,'check'),showWarnings=FALSE)
ex<-tempfile();dir.create(ex);unzip(ppt,exdir=ex)
slides<-list.files(file.path(ex,'ppt/slides'),pattern='^slide[0-9]+.xml$',full.names=TRUE)
checks<-list();check<-function(n,v){stopifnot(isTRUE(v));checks[[n]]<<-TRUE}
check('twenty_slides',length(slides)==20)
keys<-c('facts','math','models','misleading','verification','reminder')
for(i in seq_along(keys)){
 doc<-read_xml(file.path(ex,'ppt/slides/charts',paste0('chart',i,'.xml')))
 actual<-as.numeric(xml_text(xml_find_all(doc,'.//*[local-name()="ser"]/*[local-name()="val"]//*[local-name()="v"]')))
 z<-d$charts[[keys[i]]];expected<-if(!is.null(z$series))unlist(lapply(z$series,`[[`,'values'))else unlist(z$values)
 check(paste0('chart_',keys[i],'_matches_R'),length(actual)==length(expected)&&max(abs(actual-expected))<1e-12)
 check(paste0('chart_',keys[i],'_starts_at_zero'),all(as.numeric(xml_attr(xml_find_all(doc,'.//*[local-name()="valAx"]/*[local-name()="scaling"]/*[local-name()="min"]'),'val'))==0))
}
check('six_editable_workbooks',length(list.files(file.path(ex,'ppt/embeddings'),pattern='xlsx$'))==6)
alltext<-paste(vapply(slides,function(f)paste(xml_text(xml_find_all(read_xml(f),'.//*[local-name()="t"]')),collapse=' '),''),collapse='\n')
check('both_authors',all(vapply(c('LINYUNIAN','PAN ZHENGYU'),grepl,TRUE,x=alltext,fixed=TRUE)))
check('notes_all_twenty',length(list.files(file.path(ex,'ppt/notesSlides'),pattern='^notesSlide[0-9]+.xml$'))==20)
nt<-fromJSON(file.path(pack,'evidence/integrated_notes.json'));check('eighteen_minutes_plus_backup',sum(nt$seconds)==1080&&all(tail(nt$seconds,2)==0))
pt<-system2('pdftotext',c(shQuote(pdf),'-'),stdout=TRUE);pt<-paste(pt,collapse='\n')
check('pdf_contains_latest_primary_and_ablation',all(vapply(c('43.94%','44.64%','4.02%','2.01%','10.95','LINYUNIAN','PAN ZHENGYU'),grepl,TRUE,x=pt,fixed=TRUE)))
info<-system2('pdfinfo',shQuote(pdf),stdout=TRUE);pages<-as.integer(sub('Pages:[[:space:]]*','',grep('^Pages:',info,value=TRUE)))
check('pdf_twelve_pages',pages==12)
prov<-fromJSON(file.path(pack,'evidence/integrated_provenance.json'))
check('all_R_sources_unchanged',all(vapply(names(prov$source_sha256),function(f)digest(file=f,algo='sha256')==prov$source_sha256[[f]],TRUE)))
freeze<-fromJSON('Followup_Validation/protocol/freeze.json')
check('frozen_experiment_unchanged',all(vapply(names(freeze$files_sha256),function(f)digest(file=f,algo='sha256')==freeze$files_sha256[[f]],TRUE)))
write_json(list(checks=checks,checks_passed=length(checks),slide_count=length(slides),report_pages=pages,pptx_sha256=digest(file=ppt,algo='sha256'),pdf_sha256=digest(file=pdf,algo='sha256'),model_calls=0,notes='Final rendered slides and all PDF pages inspected separately. Checks do not claim Microsoft PowerPoint application validation.'),file.path(build,'check/integrated_validation.json'),pretty=TRUE,auto_unbox=TRUE)
cat('Passed',length(checks),'artifact/evidence checks.\n')
