# Author-designed, deliberately false beliefs; never label these as real model outputs.
case <- function(wrong, reason, error, proof, verification='exact_computation_and_argument')
 list(wrong_answer=wrong,wrong_reason=reason,error_location=error,correct_argument=proof,verification=verification)
math_cases <- list(
P_Combinatorics_40=case('233',
 'The tiling count follows the Fibonacci sequence, and a 2 x 11 rectangle corresponds to F_13, taking F_1 = F_2 = 1.',
 'The Fibonacci index is one too large.',
 'With T_0=T_1=1 and T_n=T_(n-1)+T_(n-2), T_11=F_12=144.'),
P_Combinatorics_21=case('15',
 'There are 6! assignments of the six colours. A cube has 48 symmetries, so dividing by 48 gives 15 distinct colourings.',
 '48 includes reflections; the question identifies colourings only under rotations.',
 'There are 24 rotations. Distinct colours make every stabilizer trivial, so 6!/24=30.'),
P_Combinatorics_20=case('65',
 'For a 2 x n board, either add two single-cell tiles to a 2 x (n-1) board, or add an L-shaped tile and a single-cell tile in four ways to a 2 x (n-2) board. Thus T_n=T_(n-1)+4T_(n-2), with T_0=T_1=1, giving T_5=65.',
 'The recurrence omits the configurations formed by two interlocking L tiles across three columns.',
 'T_n=T_(n-1)+4T_(n-2)+2T_(n-3), with T_0=1,T_1=1,T_2=5, gives 87. Independent full-board exact-cover enumeration also gives 87.'),
P_Combinatorics_38=case('216',
 'Choose two of the four boys and one of the six girls, then assign the three different toys in 3! ways: C(4,2)*6*6=216.',
 'At least two boys includes three boys; those assignments were omitted.',
 '(C(4,2)*6+C(4,3))*3!=240.'),
P_Combinatorics_5=case('143',
 'The binary-string recurrence gives 144 admissible patterns, but the all-zero pattern selects nothing and should be removed, leaving 143 subsets.',
 'The empty set is a subset and satisfies the condition.',
 'Enumerate all 2^10 subsets or use S_0=1,S_1=2,S_n=S_(n-1)+S_(n-2); the result is 144, including the empty set.'),
P_Combinatorics_30=case('1999000',
 'After collecting terms, I place two separators for the three exponents among 2000 positions. This gives C(2000,2)=1999000 terms.',
 'Stars and bars requires 1999 stars and two bars, hence 2001 positions.',
 'Nonnegative exponent triples sum to 1999. Their number is C(2001,2)=2001000.'),
P_Combinatorics_18=case('4753',
 'Give each of a, b and c one unit first. There are then 96 units left to distribute, giving C(98,2)=4753 ordered triples.',
 'This counts positive triples and excludes allowed zero components.',
 'Nonnegative triples summing to 99 are counted by C(101,2)=5050.'),
P_Combinatorics_7=case('89',
 'The arrangements follow the Fibonacci recurrence. With F_1=F_2=1, eleven seats correspond to F_11=89.',
 'The base cases are T_1=1,T_2=2; the required Fibonacci index is 12.',
 'Every movement is a disjoint adjacent swap or a fixed seat. T_11=T_10+T_9=144.'),
P_Combinatorics_31=case('512',
 'Each of the three cookies can independently go to any of eight dogs, giving 8^3=512 outcomes.',
 'The cookies are identical; independent labelled-cookie assignments overcount allocations.',
 'The eight nonnegative dog counts sum to 3, giving C(10,7)=120.'),
P_Inequality_49=case('-3',
 'At x=y=z=1, I evaluate all three absolute-value terms as zero, leaving -3. By symmetry, I take this equal-variable choice to give the minimum.',
 'At that point each absolute-value term is 1, not 0; symmetry alone also does not prove a minimum.',
 'Add |A|+|B|>=2|x|, |A|+|C|>=2|y| and |B|+|C|>=2|z| for A=x+y-z,B=x-y+z,C=-x+y+z. The expression is nonnegative, with equality at x=y=z=0 (also at equal positive values).',
 'analytic_bound_and_equality_witness'),
P_Inequality_8=case('No minimum is attained; the infimum is 0',
 'Since all x_i are strictly positive, the inequality between the power sum and the product term is strict. The difference approaches zero as all x_i approach zero, but cannot attain it.',
 'Strict positivity does not force strict inequality. All equal positive inputs attain zero.',
 'Let S=sum x_i and P=product x_i. Convexity gives sum x_i^(n+1)>=S^(n+1)/n^n; AM-GM gives PS<=S^(n+1)/n^n. Thus the difference is nonnegative and all x_i=t>0 attain zero.',
 'analytic_bound_and_equality_witness'),
P_Inequality_4=case('1',
 'Setting t=sqrt(x^2+1), the expression becomes t+1/t. Applying AM-GM gives t+1/t >= sqrt(t*(1/t))=1, so I take 1 as the minimum.',
 'AM-GM for a sum has a factor of 2; a weaker lower bound also need not be attained.',
 't>=1 and t+1/t>=2, with equality at t=1, or x=0.',
 'analytic_bound_and_equality_witness'),
P_Inequality_24=case('No minimum is attained; the infimum is 0',
 'The expression factors as ab(a+b)(a-b)^2. Because a and b are positive, I treat every factor as positive. Scaling both toward zero makes the expression approach zero without reaching it.',
 '(a-b)^2 can be zero even when a and b are positive.',
 'The exact factorization is ab(a+b)(a-b)^2>=0. Any a=b>0 attains zero.',
 'analytic_factorization_and_equality_witness'),
P_Inequality_13=case('0',
 'The quadratic part is half the sum of (a-b)^2, (b-c)^2 and (a-c)^2. It is minimized when a=b=c=3, so I report the minimum as 0.',
 'The final linear term -(a+b+c)=-9 was omitted.',
 'The full expression is ((a-b)^2+(b-c)^2+(a-c)^2)/2-9>=-9, attained at (3,3,3).',
 'analytic_bound_and_equality_witness'),
P_Inequality_15=case('No minimum is attained; the infimum is 0',
 'The quartic sum is strictly greater than abc(a+b+c) for positive inputs. Scaling the variables toward zero makes their difference approach zero, but positivity prevents equality.',
 'Positive equal variables satisfy equality; the asserted strictness is false.',
 'Weighted AM-GM gives 2a^4+b^4+c^4>=4a^2bc and its cyclic forms. Adding proves sum a^4>=abc(a+b+c). Equality holds at a=b=c>0.',
 'analytic_bound_and_equality_witness'),
P_Inequality_26=case('1',
 'The first fraction approaches 1 when |a+b| grows, while the subtracted fractions are nonnegative. I therefore take 1 as the largest possible value.',
 'This ignores dependence between the three fractions and mistakes a loose upper bound for an attainable maximum.',
 'Put x=|a|,y=|b|,z=|a+b|. Multiplication by the positive denominator (1+x)(1+y)(1+z) gives z-x-y-2xy-xyz<=0. Equality occurs at a=b=0.',
 'analytic_bound_and_equality_witness'),
`P_Number-Theory_24`=case('2',
 'By Fermat\'s little theorem, I take 2^32 to be congruent to 1 modulo 641, so adding 1 gives remainder 2.',
 'Fermat gives exponent 640, not an arbitrary exponent such as 32.',
 'Exact repeated modular squaring gives 2^32 mod 641=640, so the requested remainder is 0.'),
`P_Number-Theory_27`=case('2',
 'In the repunit formula n=2(10^1980-1)/9, I replace the power 10^1980 by 10 under the modulus. This leaves 2(10-1)/9=2.',
 'There is no justified exponent reduction giving 10^1980 congruent to 10 modulo 1982.',
 'Starting with r=0 and applying r=(10r+2) mod 1982 exactly 1980 times returns 0, without storing the enormous integer.'),
`P_Number-Theory_71`=case('1',
 'The powers of 12 and 5 are coprime, so their smallest possible positive difference should be 1.',
 'Coprimality does not imply that this restricted pair of powers can be consecutive.',
 'The difference is coprime to 2,3,5, excluding magnitudes 0 and 2 through 6. The equation 12^m-5^n=1 is impossible modulo 4. If 5^n-12^m=1 then n=2k; (5^k-1)(5^k+1)=2^(2m)3^m. Since gcd of the factors is 2 and 5^k+1 has exactly one factor of 2, either 5^k+1=2 (impossible) or 5^k+1=2*3^m and 5^k-1=2^(2m-1). Their difference would imply 3^m-4^(m-1)=1, impossible modulo 3. Magnitude 7 is attained at m=n=1.',
 'analytic_exclusion_plus_finite_sanity_check'),
`P_Number-Theory_17`=case('4489',
 '4489 is 67^2 and has a repeated pair of digits, so I take it to satisfy the required aabb pattern.',
 'The last two digits must be equal too; 4489 has unequal final digits.',
 'Exhaustively test squares from 32^2 through 99^2 for the four-digit aabb pattern. Only 88^2=7744 satisfies it.'),
`P_Number-Theory_32`=case('7',
 'I reduce the exponent 105 modulo 5 to 1, giving 3^105+4^105 congruent to 3+4=7 modulo 11.',
 '105 modulo 5 is 0, not 1; both bases have fifth power congruent to 1.',
 '3^5 mod 11=4^5 mod 11=1, so both 105th powers have remainder 1 and their sum has remainder 2.'),
`P_Number-Theory_12`=case('75',
 'A two-digit number ending in 5 has a square ending in 5, so 75 should be another automorphic number besides 25.',
 'The last two digits must match the whole number, not just its last digit; 75^2 ends in 25.',
 'Enumerating a=10,...,99 with a^2 mod 100=a gives exactly 25 and 76; exclude 25.'),
`P_Number-Theory_42`=case('17',
 'Each question gives the product of three entries, so covering fifty entries requires ceil(50/3)=17 questions. I can multiply those answers to recover the total product.',
 'Overlapping entries cannot be ignored. A query subset must include each index an odd number of times, not merely cover it.',
 'Encode signs over GF(2). Each query row has ones on three consecutive cyclic positions. The 50x50 query matrix has rank 50; the unique coefficient vector representing total parity is all ones, hence all 50 distinct queries are necessary and sufficient. This also excludes an adaptive shortcut: after any proper subset, two sign assignments agree on all observed queries and have different total parity.'),
`P_Number-Theory_67`=case('50',
 'Even n give even composite values, while odd n give odd values. There are fifty odd n from 1 to 99, so I count fifty primes.',
 'Odd does not mean prime; every odd n greater than 1 admits a nontrivial factorization.',
 'n=1 gives 5. Even n>=2 give even numbers greater than 2. For odd n=2k+1>=3, write b=2^k and use n^4+4b^4=(n^2-2nb+2b^2)(n^2+2nb+2b^2). The first factor=(n-b)^2+b^2>1. Thus only n=1 works.',
 'analytic_factorization_and_small_integer_checks'),
`P_Number-Theory_13`=case('31',
 'Both powers increase with their positive exponents, so the smallest absolute difference must occur at m=n=1, giving 36-5=31.',
 'The absolute difference need not increase when either exponent increases; m=1,n=2 gives a smaller value.',
 'A positive difference can end only in 1 or 9. Magnitude 1 would require 36^m-5^n=1; factoring (6^m-1)(6^m+1) contradicts the prime factors of 5^n. Magnitude 9 requires 5^n-36^m=9, impossible modulo 6. Thus the smallest candidate is 11, attained at m=1,n=2.',
 'analytic_exclusion_plus_finite_sanity_check'),
P_Polynomial_32=case('0',
 'Any root r of f satisfies r^5=1. I treat r^5 as another root of f, so every root of f also makes f(x^5) vanish and the remainder should be 0.',
 'The value r^5=1 is not a root of f: f(1) is nonzero.',
 'Modulo f(x), x^5=1, so f(x^5)=f(1)=5. Polynomial long division confirms the constant remainder.'),
P_Polynomial_23=case('1',
 'Since p(x) divides x^7-1, I use x^7 congruent to 0 modulo p(x). Then p(x^7) reduces to p(0)=1.',
 'x^7 is congruent to 1, not 0, modulo p(x).',
 'Modulo p(x), x^7=1 and p(x^7)=p(1)=7. Polynomial long division confirms this.'),
P_Polynomial_50=case('5',
 'A repeated root requires the derivative to vanish. For f\'(x)=5x^4-2ax-a, I evaluate f\'(-1) as 5-2a+a=5-a, giving a=5.',
 'The signs at x=-1 are reversed; the derivative there is 5+a.',
 'f(-1)=0 for all a and f\'(-1)=5+a, hence a=-5; the second derivative at -1 is then -10, so multiplicity is exactly two.'),
P_Polynomial_24=case('0',
 'The expression is a product of four consecutive terms in x^3. I treat that product as nonnegative, with zero attained when one factor vanishes.',
 'Consecutive real factors can have an odd number of negative factors; x^3 is not restricted to integers.',
 'Set t=x^3 and u=t^2+3t. The product is (u+1)^2-1>=-1. Values t=(-3+sqrt(5))/2 or (-3-sqrt(5))/2 give u=-1, and a real cube root exists.',
 'analytic_bound_and_equality_witness'),
P_Polynomial_1=case('x-1',
 'The numerator is zero at x=1, so it has one factor x-1. Dividing by (x-1)^2 should therefore leave the remainder x-1.',
 'A zero at 1 alone does not determine this remainder; the derivative also vanishes at 1.',
 'For the polynomial numerator F, F(1)=0 and F\'(1)=n(n+1)-n(n+1)=0. Thus (x-1)^2 divides F and the remainder is identically zero.',
 'analytic_identity_and_polynomial_division_checks'),
P_Polynomial_40=case('-4.5',
 'Minimizing a^2-3a and b^2-3b separately gives -9/4 for each, so adding them gives the minimum -9/2.',
 'The cross term ab was omitted, so separate minima do not solve the original problem.',
 'Put a=1+u,b=1+v. The expression equals u^2+uv+v^2-3, and u^2+uv+v^2=(u+v/2)^2+3v^2/4>=0. The minimum -3 occurs at a=b=1.',
 'analytic_bound_and_equality_witness'),
P_Polynomial_47=case('-120',
 'With y=x+1, write the polynomial as (1-(y-1)^10)/y. The coefficient of y^3 in (y-1)^10 is -C(10,3)=-120, so I take a_2=-120.',
 'The minus sign before (y-1)^10 flips that coefficient.',
 'The coefficient of y^3 in the numerator is +120, hence the coefficient of y^2 after division by y is 120.'),
P_Polynomial_17=case('2',
 'Even without fixed points, a polynomial can swap two real numbers, f(a)=b and f(b)=a. Both would solve f(f(x))=x, so I take the maximum to be 2.',
 'A real two-cycle would force a fixed point by continuity of f(x)-x, contradicting the premise.',
 'The continuous function g(x)=f(x)-x never vanishes, so it has one strict sign on the real line. If f(x)>x everywhere, f(f(x))>f(x)>x; the everywhere-less case is analogous. Therefore there are no real solutions.',
 'analytic_continuity_proof_not_finite_enumeration'),
P_Polynomial_11=case('10',
 'The power sums modulo 5 repeat with period six. I count the remainder 4 once per period, so sixty consecutive indices give ten occurrences.',
 'The remainder 4 appears twice, not once, in each six-term period.',
 's_0=2,s_1=6,s_n=6s_(n-1)-s_(n-2). Modulo 5 the cycle is 2,1,4,3,4,1, so indices 61 through 120 contain twenty occurrences of 4.'),
P_Sequence_28=case('u-v',
 'Both recurrences average the same two previous values, so I assume they shift the two sequences equally and preserve the original gap.',
 'The two averages have different weights; their gap contracts by a factor of six.',
 'd_n=v_n-u_n=d_(n-1)/6. Also 2u_n+3v_n is invariant, so both sequences converge and their limit difference is zero.',
 'analytic_recurrence_and_exact_coefficient_check'),
P_Sequence_42=case('600',
 'The largest power of two below 1324 is 1024. The Josephus survivor is twice the excess, so 2*(1324-1024)=600.',
 'This omits the +1 needed for one-based labels.',
 'For removal of every second person, J(n)=2(n-2^floor(log2(n)))+1. Direct circular elimination independently gives label 601.'),
P_Sequence_20=case('144',
 'The recurrence is Fibonacci-type with values 1,2,3,5,..., and I place a_10 at F_12=144.',
 'With a_1=1,a_2=2, a_10=F_11; the index was shifted by one.',
 'Allowed permutations consist of fixed positions and disjoint adjacent swaps. The recurrence a_n=a_(n-1)+a_(n-2) gives a_10=89; a matching-count DP confirms it.'),
P_Sequence_11=case('2',
 'The sum telescopes to 2-1/x_101. Since x_101 is extremely large, I drop the reciprocal term and take the integer part to be 2.',
 'The positive reciprocal is not zero; dropping it changes the floor at an integer boundary.',
 'The exact sum is 2-1/x_101. Since x_3=21/16>1 and the positive sequence increases, 0<1/x_101<1. Thus the finite sum is strictly between 1 and 2, and its floor is 1.',
 'analytic_strict_bound_avoids_floating_point_rounding'),
P_Sequence_21=case('50',
 'With a_0=0 and a_1=1, I extend the sequence as an arithmetic progression, so a_n=n and a_50=50.',
 'The functional equation forces a_2=4, already contradicting an arithmetic progression.',
 'Set m=n to get a_0=0 and n=0 to get a_(2m)=4a_m. With m=n+2 obtain a_(n+2)=2a_(n+1)-a_n+2. The initial values then imply a_n=n^2 and a_50=2500.'),
P_Sequence_19=case('1',
 'I treat the initial block 1,1,-1 as a repeating cycle of length three. Since 1964 leaves remainder two on division by three, I take a_1964=1.',
 'The recurrence does not repeat the initial three values; the actual period is seven.',
 'Iterating the sign recurrence yields the seven-term cycle 1,1,-1,-1,-1,1,-1. Since 1964 mod 7=4, the value is -1.'),
P_Sequence_40=case('123',
 'Count the permutations made from fixed positions and disjoint swaps of neighbouring positions on the circle. This gives F_11+F_9=89+34=123.',
 'The full clockwise and full anticlockwise rotations are also allowed and are not disjoint-swap matchings.',
 'Cycle matchings give 123 possibilities and the two full shifts give two more, for 125. An independent permanent DP over all allowed positions confirms 125.')
)
